services:
  postgres:
    image: postgres
    restart: always
    container_name: rajvansh-js
    volumes:
      - ./local/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
